name: Auto Merge Manager

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize
      - ready_for_review
  pull_request_review:
    type: [submitted]

concurrency:
  group: auto-merge-manager-${{ github.ref }}
  cancel-in-progress: false

jobs:
  #
  # Common
  #
  query-pr:
    name: Query Pull Request
    runs-on: ubuntu-20.04

    # We need to duplicate the base check here due to `pull_request_review`.
    if: >
      (startsWith(github.event.pull_request.base.ref, 'main')) &&
      (github.event.action == 'ready_for_review' ||
      !github.event.pull_request.draft)

    steps:
      - name: Query Pull Request ID
        id: query_pr_id
        uses: octokit/graphql-action@v2.2.20
        env:
          GITHUB_TOKEN: ${{ secrets.TMBOT_TOKEN }}
          INPUT_OWNER: ${{ github.event.repository.owner.login }}
          INPUT_NAME: ${{ github.event.repository.name }}
          INPUT_NUMBER: ${{ github.event.pull_request.number }}
        with:
          query: |
            query ($owner: String!, $name: String!, $number: Int!) {
              repository(owner: $owner, name: $name) {
                pullRequest(number: $number) {
                  id
                }
              }
            }
    outputs:
      pr_id: ${{fromJSON(steps.query_pr_id.outputs.data).repository.pullRequest.id}}

  #
  # Disable Auto Merge
  #
  disable-auto-merge:
    name: Disable Auto Merge
    runs-on: ubuntu-20.04
    needs: [query-pr]
    steps:
      - name: Disable Pull Request Auto Merge
        uses: octokit/graphql-action@v2.2.20
        if: >
          contains(github.event.pull_request.labels.*.name, 'no-auto-merge') ||
          github.event.action == 'edited'
        env:
          GITHUB_TOKEN: ${{ secrets.TMBOT_TOKEN }}
          INPUT_PULL_REQUEST_ID: ${{ needs.query-pr.outputs.pr_id }}
        with:
          query: |
            mutation ($pull_request_id: ID!) {
              disablePullRequestAutoMerge(input: { pullRequestId: $pull_request_id }) {
                pullRequest {
                  id
                }
              }
            }

  #
  # Enable Auto Merge
  #
  enable-auto-merge:
    name: Enable Auto Merge
    runs-on: ubuntu-20.04
    if: |
      ! contains(github.event.pull_request.labels.*.name, 'no-auto-merge')
    needs: [query-pr, disable-auto-merge]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TMBOT_TOKEN }}

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # The following script outputs `steps.fmt.outputs.formatted_pr_body`.
      - name: Format PR Body
        id: fmt
        run: python3 .github/workflow-scripts/format-pr-body.py
        env:
          RAW_PR_BODY: ${{ github.event.pull_request.body }}

      - name: Get Merge Method
        id: config
        run: |
          base_ref=${{ github.event.pull_request.head.ref }};

          case $base_ref in
            story/*)
              merge_method=REBASE;
              ;;
            *)
              merge_method=SQUASH;
              ;;
          esac

          echo "::set-output name=merge_method::$merge_method";

      - name: Enable Pull Request Auto Merge
        uses: octokit/graphql-action@v2.2.20
        env:
          GITHUB_TOKEN: ${{ secrets.TMBOT_TOKEN }}
          INPUT_PULL_REQUEST_ID: ${{ needs.query-pr.outputs.pr_id }}
          INPUT_MERGE_METHOD: ${{ steps.config.outputs.merge_method }}
          INPUT_BODY: ${{ toJSON(steps.fmt.outputs.formatted_pr_body) }}
        with:
          query: |
            mutation (
              $pull_request_id: ID!
              $merge_method: PullRequestMergeMethod
              $body: String
            ) {
              enablePullRequestAutoMerge(
                input: {
                  pullRequestId: $pull_request_id
                  mergeMethod: $merge_method
                  commitBody: $body
                }
              ) {
                pullRequest {
                  id
                }
              }
            }
